# Generated by Django 6.0.3 on 2026-03-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mentors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('auther_image', models.ImageField(upload_to='')),
                ('title', models.CharField()),
                ('auther', models.CharField()),
            ],
        ),
    ]
